# Generated by Django 4.1.5 on 2023-02-05 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_number_of_passenger', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(default='b', max_length=5)),
                ('license_plate', models.CharField(default='', max_length=20)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=50)),
                ('arrival_time', models.DateTimeField()),
                ('number_of_passengers', models.IntegerField(default=1)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(default='All', max_length=5)),
                ('special_request', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uber.driverinfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
