# Generated by Django 4.1.5 on 2023-02-05 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, default=None, related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
