# Generated by Django 4.1.5 on 2023-02-01 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_requestride_delete_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestride',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
