# Generated by Django 4.1.5 on 2023-02-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_alter_requestride_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='RequestRide',
        ),
    ]
