# Generated by Django 4.1.5 on 2023-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_alter_ride_number_of_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(default='Sedan', max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('All', 'All'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Minivan', 'Minivan')], max_length=10),
        ),
    ]
