# Generated by Django 4.1.5 on 2023-02-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_ride_delete_question_delete_requestride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='num_passenger',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ride',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
