# Generated by Django 4.1.5 on 2023-02-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_alter_driverinfo_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('All', 'All'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Minivan', 'Minivan')], default='All', max_length=10),
        ),
    ]
