# Generated by Django 4.1.5 on 2023-02-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='maximum_number_of_passenger',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Minivan', 'Minivan')], default='Sedan', max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='number_of_passengers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
