# Generated by Django 4.1.5 on 2023-02-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber', '0006_alter_driverinfo_maximum_number_of_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='sharer',
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1)),
                ('ride', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uber.ride')),
                ('sharer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
