# Generated by Django 4.1.5 on 2023-02-02 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0006_rename_num_passenger_ride_number_of_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='ride',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 5, 25, 9, 178200, tzinfo=datetime.timezone.utc)),
        ),
    ]
