# Generated by Django 4.1.5 on 2023-02-02 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0008_alter_ride_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
