# Generated by Django 4.1.5 on 2023-02-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0009_ride_arrival_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arrival_time',
            new_name='arrival_date',
        ),
    ]
