# Generated by Django 4.1.5 on 2023-02-02 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0010_rename_arrival_time_ride_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
