# Generated by Django 4.1.5 on 2023-02-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0012_ride_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
