# Generated by Django 4.1.5 on 2023-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0013_rename_owner_id_ride_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='can_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
