# Generated by Django 4.1.5 on 2023-02-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0016_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.IntegerField(default=1),
        ),
    ]
