# Generated by Django 4.1.5 on 2023-02-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0020_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_type',
        ),
    ]
