# Generated by Django 4.1.5 on 2023-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0021_remove_ride_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
