# Generated by Django 4.1.5 on 2023-02-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0023_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_request',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
