# Generated by Django 4.1.5 on 2023-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0025_alter_ride_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='special_request',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
