# Generated by Django 4.1.5 on 2023-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0027_driverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='maximum_number_of_passenger',
            field=models.IntegerField(default=1),
        ),
    ]
