# Generated by Django 4.1.5 on 2023-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0028_driverinfo_maximum_number_of_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(default='b', max_length=50),
        ),
    ]
