# Generated by Django 4.1.5 on 2023-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0029_driverinfo_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='license_plate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(default='b', max_length=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='a', max_length=5),
        ),
    ]
