# Generated by Django 4.1.5 on 2023-02-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0030_driverinfo_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='All', max_length=5),
        ),
    ]
