# Generated by Django 4.1.5 on 2023-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0031_ride_isconfirmed_alter_ride_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='isCompete',
            field=models.BooleanField(default=False),
        ),
    ]
