# Generated by Django 4.1.5 on 2023-02-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0032_ride_iscompete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='isCompete',
            new_name='isComplete',
        ),
    ]
