# Generated by Django 4.1.5 on 2023-02-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0034_ride_driver_alter_ride_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='license_plate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
