# Generated by Django 4.1.5 on 2023-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0035_ride_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='license_plate',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
